app/models.py
from datetime import datetime
from . import db


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64),
                      nullable=False, unique=True, index=True)
    username = db.Column(db.String(64),
                         nullable=False, unique=True, index=True)
    is_admin = db.Column(db.Boolean)
    password_hash = db.Column(db.String(128))
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    bio = db.Column(db.Text())
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    avatar_hash = db.Column(db.String(32))

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from config import config


bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    db.init_app(app)

    from .hacks import hacks as hacks_blueprint
    app.register_blueprint(hacks_blueprint)

    return app

app/hacks/__init__.py
from flask import Blueprint

hacks = Blueprint('hacks', __name__)

from . import routes

app/hacks/routes.py
from flask import render_template
import googlemaps
from . import hacks
import urllib2
#import yaml
import json
@hacks.route('/')
def index():
    return render_template('hacks/index.html')

@hacks.route('/workshop')
def workshop():
	final_url=('https://api.meetup.com/2/open_events?key=3947c3e2d3e196a1d4292396f334f&and_text=False&country=in&offset=0&format=json&lon=77.2719131&limited_events=False&photo-host=public&page=500&radius=25.0&lat=28.5440551&category=18%2C2%2C6%2C34&desc=False&status=upcoming&sig_id=161835092&sig=e5b75df3659d864d9ddbd92a5711545ff0f1ccdc')
	json_obj=urllib2.urlopen(final_url)
	data=json.load(json_obj)
        gmaps = googlemaps.Client(key='AIzaSyB3wNLhjT9wEyeFvSN1yjp3iEdTFp76pt8')
#        import pdb; pdb.set_trace()
        new_list=[]
	for data1 in data['results']:
            if 'venue' in data1.keys():
                matrix=gmaps.distance_matrix("%s, %s " %(str(data1['venue']['lat']),str(data1['venue']['lon'])),"okhla,delhi")
                new_list.append(matrix)
            else:
                continue
        #return matrix
	return render_template('hacks/workshop.html',data=new_list)
	#for data1 in data['results']:
	#	return data1

@hacks.route('/social_events')
def social_events():
	final_url=('https://api.meetup.com/2/open_events?key=3947c3e2d3e196a1d4292396f334f&and_text=False&country=in&offset=0&format=json&lon=77.2719131&limited_events=False&photo-host=public&page=500&radius=25.0&lat=28.5440551&category=16%2C25%2C4%2C13%2C30%2C31%2C35&desc=False&status=upcoming&sig_id=161835092&sig=e5b75df3659d864d9ddbd92a5711545ff0f1ccdc')
	json_obj=urllib2.urlopen(final_url)
	data=json.load(json_obj)
	return render_template('hacks/social_events.html')

@hacks.route('/entertainment')
def entertainment():
	final_url=('https://api.meetup.com/2/open_events?key=3947c3e2d3e196a1d4292396f334f&and_text=False&country=in&offset=0&format=json&lon=77.2719131&limited_events=False&photo-host=public&page=500&radius=25.0&lat=28.5440551&category=10%2C11%2C29%2C3%2C23%2C20%2C27%2C9%2C32%2C1&desc=False&status=upcoming&sig_id=161835092&sig=e5b75df3659d864d9ddbd92a5711545ff0f1ccdc')
	json_obj=urllib2.urlopen(final_url)
	data=json.load(json_obj)
	for data1 in data['results']:
		if data1['venue']:
			data1['venue']['lon']
			data1['venue']['lat']

	return render_template('hacks/entertainment.html')

@hacks.route('/hobby')
def hobby():
	final_url=('https://api.meetup.com/2/open_events?key=3947c3e2d3e196a1d4292396f334f&and_text=False&country=in&offset=0&format=json&lon=77.2719131&limited_events=False&photo-host=public&page=500&radius=25.0&lat=28.5440551&category=22%2C24%2C28%2C8%2C15%2C5%2C21%2C26%2C14%2C33&desc=False&status=upcoming&sig_id=161835092&sig=e5b75df3659d864d9ddbd92a5711545ff0f1ccdc')
	json_obj=urllib2.urlopen(final_url)
	data=json.load(json_obj)
	return render_template('hacks/hobby.html')

@hacks.route('/user/<username>')
def user(username):
    return render_template('hacks/user.html', username=username)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Talks{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('hacks.index') }}">Talks</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('hacks.index') }}">Home</a></li>
                <li><a href="{{ url_for('hacks.user', username='miguel') }}">Profile</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/hacks/entertainment.html
{% extends "hacks/index.html" %}

app/templates/hacks/hobby.html
{% extends "hacks/index.html" %}

app/templates/hacks/index.html
{% extends "base.html" %}

{% block page_content %}
<h1>Hello, World!</h1>
{% endblock %}

app/templates/hacks/social_events.html
{% extends "hacks/index.html" %}

app/templates/hacks/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {{ username }}!</h1>
</div>
{% endblock %}

app/templates/hacks/workshop.html
{% extends "base.html" %}

{% block page_content %}
{%for data1 in data%}
<p> address1 = </br>{{data1}} </p>
{%endfor%}

{% endblock %}